"""Configuration and data-root discovery.

Raw datasets are intentionally kept outside Git. The application consumes the
small derived artifacts generated by the offline ETL, while this module gives
the ETL a deterministic way to find the raw source tree.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

DATASET_DIRS = (
    "store-visits-rice",
    "urban-heat-index-rice",
    "daily-weather-rice",
    "core-poi-geometry-rice",
    "spend-patterns-rice",
    "daily-spend-brand-and-state-rice",
)


@dataclass(frozen=True)
class ProjectPaths:
    repo_root: Path
    data_root: Path | None
    artifact_root: Path

    def raw_dataset(self, name: str) -> Path:
        if name not in DATASET_DIRS:
            raise KeyError(f"Unknown dataset: {name}")
        if self.data_root is None:
            return self.repo_root / name
        return self.data_root / name


def _contains_dataset_dirs(path: Path) -> bool:
    return path.is_dir() and all((path / name).is_dir() for name in DATASET_DIRS)


def resolve_data_root(repo_root: Path | None = None, explicit: str | Path | None = None) -> Path | None:
    """Resolve the raw data directory without silently choosing a wrong path."""

    root = Path(repo_root or Path(__file__).resolve().parents[2])
    candidates: list[Path] = []
    if explicit:
        candidates.append(Path(explicit).expanduser())
    env_root = os.getenv("MOBILITY_DATA_ROOT")
    if env_root:
        candidates.append(Path(env_root).expanduser())
    candidates.extend((root / "Rice WC Hack", root))

    for candidate in candidates:
        candidate = candidate.resolve()
        if _contains_dataset_dirs(candidate):
            return candidate
    return None


def project_paths(repo_root: Path | None = None, explicit_data_root: str | Path | None = None) -> ProjectPaths:
    root = Path(repo_root or Path(__file__).resolve().parents[2]).resolve()
    return ProjectPaths(
        repo_root=root,
        data_root=resolve_data_root(root, explicit_data_root),
        artifact_root=root / "dashboard" / "cache",
    )


def require_data_root(paths: ProjectPaths) -> Path:
    if paths.data_root is None:
        expected = ", ".join(DATASET_DIRS)
        raise FileNotFoundError(
            "Raw mobility data was not found. Set MOBILITY_DATA_ROOT to a directory "
            f"containing these datasets: {expected}"
        )
    return paths.data_root
